version: '3.9'

services:
  app:
    container_name: portfolio
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    networks:
      - default

networks:
  default:
    name: traefik_network
    external: true