export * from './Icons'
export { default as logo } from './imgs/CircleLogo.svg'
export { default as logo2 } from './imgs/CircleLogo2.svg'
export { default as spainSVG } from './imgs/spain.svg'
export { default as usaSVG } from './imgs/usa.svg'
export { default as henryGames } from './imgs/henrygames.png'
export { default as rgbTech } from './imgs/rgbtech.png'
export { default as henryGamesLogo } from './imgs/henrygames-logo.png'
export { default as rgbTechLogo } from './imgs/rgbtech-logo.png'

export { default as htmlLogo } from './imgs/html.png'
export { default as cssLogo } from './imgs/css.png'
export { default as javascriptLogo } from './imgs/javascript.png'
export { default as styledComponentsLogo } from './imgs/styledcomponents.svg'
export { default as sassLogo } from './imgs/sass.png'
export { default as postcssLogo } from './imgs/postcss.png'
export { default as gimpLogo } from './imgs/gimp.png'
export { default as kritaLogo } from './imgs/krita.png'
export { default as inkscapeLogo } from './imgs/inkscape.png'
export { default as gitLogo } from './imgs/git.png'
export { default as trelloLogo } from './imgs/trello.png'
export { default as notionLogo } from './imgs/notion.png'
export { default as reactLogo } from './imgs/react.png'
export { default as nextjsLogo } from './imgs/nextjs.png'
export { default as reduxLogo } from './imgs/redux.png'
export { default as nodejsLogo } from './imgs/nodejs.png'
export { default as expressjsLogo } from './imgs/express.svg'
export { default as postgresqlLogo } from './imgs/postgresql.png'
export { default as sequelizeLogo } from './imgs/sequelize.png'
export { default as linuxLogo } from './imgs/linux.png'
export { default as windowsLogo } from './imgs/windows.png'

export { default as profilePhoto } from './imgs/profilephoto.jpg'
